algoritmo "A receita de uma padaria ao final do dia e quanto o dono deve armazenar na poupança"

var
pF,pD,rec,poup:real

inicio
escreva("Quantos pães franceses o senhor vendeu hoje? ")
leia(pF)
escreva("E quantos pães doces? ")
leia(pD)
rec<-(pF*0.12+pD*1.50)
poup<-(rec*0.10)
escreva("Senhor, a sua receita de hoje foi de ",rec," reais e você deve armazenar ",poup," reais na poupança.")

fimalgoritmo


