algoritmo "A média aritmética de alguns números"

var
n1,n2,n3,media:real

inicio
escreva("Me informe um número, ó caro senhor ")
leia(n1)
escreva("Me informe outro núemro, por favor ")
leia(n2)
escreva("Por fim, me informe mais um número, por obséquio ")
leia(n3)
escreval("Obrigado! Agora bora mostrar o resultado!")
media<-(n1+n2+n3)/3

escreva("Oh aí, canxa, esse é a média aritmética dos seus números ",media)

fimalgoritmo