algoritmo "Quantos litros de gasolina um motorista pode colocar no tanque do seu automóvel com base no preço que ele pagou"

var
preco,gas,L:real

inicio
escreva("O litro da gasolina está custando quanto atualmente? ")
leia(gas)
escreva("Olá senhor, peço que informe quantos reais o senhor vai pagar para eu encher o tanque do seu automóvel. No fim, direi a você quantos litros deu ")
leia(preco)
L<-(preco/gas)
escreva("Senhor, eu coloquei no seu tanque ",L," litros de gasolina")

fimalgoritmo


